#!/bin/bash

R_ALGORITHM_PATH=$1
R_EXEC_DIR=$2
TMP_DIR_PATH=$3

TIMEOUT=12600

COMMAND="timeout $TIMEOUT Rscript $R_ALGORITHM_PATH $R_EXEC_DIR $TMP_DIR_PATH"

NUMBER_OF_TIMEOUTS=0

echo "Executing R script..."
if $COMMAND
then
  PROCESS_OUTPUT=$?
  if [ $PROCESS_OUTPUT -ne 0 ]
  then
    exit 1
  fi
else
  NUMBER_OF_TIMEOUTS=$(($NUMBER_OF_TIMEOUTS+1))
  echo "NUMBER OF TIMEOUTS $NUMBER_OF_TIMEOUTS"
  exit 1
fi
