#!/bin/bash
DIRNAME=`dirname $0`
LOG4J=log4j.properties
cd $DIRNAME/..
if [ -f $LOG4J ]; then
CONF_LOG=-Dlog4j.configuration=file:$LOG4J
else
CONF_LOG=
fi


FILE_NAME=`ls LT52150651988052CUB00.tar.gz | cut -d . -f1`
MTL_FILE=`ls $FILE_NAME*MTL*`

java $CONF_LOG -cp target/sebal-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.sebal.BulkMain manager.conf > /dev/null &